# Generated by Django 5.0.2 on 2026-03-31 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('product_type', models.CharField(choices=[('ring', 'Кольцо'), ('bracelet', 'Браслет'), ('earrings', 'Серьги')], max_length=20)),
                ('glb_file', models.FileField(blank=True, null=True, upload_to='builder_models/')),
                ('allow_engraving', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='jewelry/')),
            ],
        ),
        migrations.CreateModel(
            name='BuilderOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('ring', 'Кольцо'), ('bracelet', 'Браслет'), ('earrings', 'Серьги')], max_length=20)),
                ('material', models.CharField(max_length=50)),
                ('stone', models.CharField(blank=True, max_length=50)),
                ('engraving', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.buildermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jewelry')),
            ],
        ),
    ]
