# Generated by Django 5.0.2 on 2026-04-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderorder',
            name='customer_name',
            field=models.CharField(default='unknown', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builderorder',
            name='phone',
            field=models.CharField(default='unknown', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='customer_name',
            field=models.CharField(default='unknown', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogorder',
            name='phone',
            field=models.CharField(default='unknown', max_length=30),
            preserve_default=False,
        ),
    ]
