# Generated by Django 5.0.2 on 2026-04-13 08:22

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_builderorder_customer_name_builderorder_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='image',
            field=models.ImageField(default='exit', upload_to=main.models.upload_to),
            preserve_default=False,
        ),
    ]
