# Generated by Django 5.0.2 on 2026-04-21 11:58

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_jewelry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_to),
        ),
    ]
