# Generated by Django 5.0.2 on 2026-04-21 12:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_jewelry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
